services:
  mongodb:
    build:
      context: ./ex1/api_dados
      dockerfile: Dockerfile.mongo
    container_name: mongodb_autoRepair
    networks:
      - repairs-network

  api:
    build: 
      context: ./ex1/api_dados
      dockerfile: Dockerfile # O teu servidor de API minimalista
    container_name: api_dados
    ports:
      - "16025:16025"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/autoRepair
    depends_on:
      - mongodb
    networks:
      - repairs-network

  interface:
    build:
      context: ./ex2/interface
      dockerfile: Dockerfile.interface # Dockerfile para este novo servidor
    container_name: interface_web
    ports:
      - "16026:16026"
    environment:
      - API_URL=http://api_dados:16025/repairs
    depends_on:
      - api
    networks:
      - repairs-network

networks:
  repairs-network:
    driver: bridge